version: '3'

services:

  fhir:
    container_name: fhir
    image: hapiproject/hapi:v5.6.0
    restart: always
    ports:
      - "7000:8080"
    environment:
      profiles.active: r4
      spring.datasource.url: 'jdbc:postgresql://db:5432/hapi'
      spring.datasource.username: admin
      spring.datasource.password: admin
      spring.datasource.driverClassName: org.postgresql.Driver
      jpa.properties.hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hapi.fhir.server_address: "https://HOST_NAME/fhir"
      hapi.fhir.tester.home.server_address: "https://HOST_NAME/fhir"
      #HAPI_FHIR_TESTER_0_SERVER_ADDRESS: "http://fhir.moh2.solidlines.io/fhir"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    # not needed for networking between containers but here for troubleshooting
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  db:
    driver: local

