version: '3'

services:

  fhir_HOST_NAME:
    container_name: fhir_HOST_NAME
    image: hapiproject/hapi:v5.6.0
    restart: always
    environment:
      profiles.active: r4
      spring.datasource.url: 'jdbc:postgresql://db_HOST_NAME:5432/hapi'
      spring.datasource.username: admin
      spring.datasource.password: admin
      spring.datasource.driverClassName: org.postgresql.Driver
      jpa.properties.hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hapi.fhir.server_address: "https://HOST_NAME/fhir"
      hapi.fhir.tester.home.server_address: "https://HOST_NAME/fhir"
    ports:
      - "7000:8080"
    networks:
      - HOST_NAME
    volumes:
      - /var/log/hapifhir/HOST_NAME:/usr/local/tomcat/logs
    depends_on:
      - db_HOST_NAME

  db_HOST_NAME:
    container_name: db_HOST_NAME
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    # not needed for networking between containers but here for troubleshooting
    ports:
      - "5433:5432"
    networks:
      - HOST_NAME
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  db:
    driver: local
networks:
  HOST_NAME:
    driver: bridge
